/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_test_2eproto__INCLUDED
#define PROTOBUF_C_test_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _Test Test;


/* --- enums --- */


/* --- messages --- */

struct  _Test
{
  ProtobufCMessage base;
  uint32_t id;
  char *msg;
};
#define TEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&test__descriptor) \
    , 0, NULL }


/* Test methods */
void   test__init
                     (Test         *message);
size_t test__get_packed_size
                     (const Test   *message);
size_t test__pack
                     (const Test   *message,
                      uint8_t             *out);
size_t test__pack_to_buffer
                     (const Test   *message,
                      ProtobufCBuffer     *buffer);
Test *
       test__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   test__free_unpacked
                     (Test *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Test_Closure)
                 (const Test *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor test__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_test_2eproto__INCLUDED */
